# Concept Session
## You might have noticed that data is present in multiple files in the dataset provided to you. What is the first thing that comes to your mind? 
## 'Merge them'

## You may need to bring all the data at one place by some sort of join logic and then start your analysis.

# Task-1)

## Assume that you have some data of customers with Cust_ID in one sheet of an excel file and some more data with Cust_ID in a second sheet of the same excel file. How can you join these data?
### Read data from first sheet of excel file 'customer.xlsx'

In [1]:
#Reading data from excel file
import pandas as pd
df_cust1 = pd.read_excel('customer.xlsx', sheet_name=0)
df_cust1

   Cust_ID      Name
0      101    Olivia
1      102   William
2      103    Sophia
3      104  Isabella

### Read the data from second sheet of excel file.

In [2]:
#Reading data from excel file
df_cust2 = pd.read_excel('customer.xlsx', sheet_name=1)
df_cust2

   Order_ID  Cust_ID  Order
0       222      101    789
1       223      102    465
2       224      103    674
3       225      104    564
4       226      105    589

## 1. Inner Join

In [3]:
#inner join - use intersection of index observed in both dataframes
df_cust1.set_index('Cust_ID').join(df_cust2.set_index('Cust_ID'), on='Cust_ID', how='inner')

             Name  Order_ID  Order
Cust_ID
101        Olivia       222    789
102       William       223    465
103        Sophia       224    674
104      Isabella       225    564

## 2. Outer Join

In [4]:
#outer join - use union of index observed in both dataframes
df_cust1.set_index('Cust_ID').join(df_cust2.set_index('Cust_ID'), on='Cust_ID', how='outer')

       Cust_ID      Name  Order_ID  Order
101.0      101    Olivia       222    789
102.0      102   William       223    465
103.0      103    Sophia       224    674
104.0      104  Isabella       225    564
NaN        105       NaN       226    589

## 3. Right Join

In [5]:
#right join - use only the index found in right dataframes
df_cust1.set_index('Cust_ID').join(df_cust2.set_index('Cust_ID'), on='Cust_ID', how='right')

       Cust_ID      Name  Order_ID  Order
101.0      101    Olivia       222    789
102.0      102   William       223    465
103.0      103    Sophia       224    674
104.0      104  Isabella       225    564
NaN        105       NaN       226    589

## 4. Left Join

In [6]:
#left join - use only the index found in left dataframes
df_cust1.set_index('Cust_ID').join(df_cust2.set_index('Cust_ID'), on='Cust_ID', how='left')

             Name  Order_ID  Order
Cust_ID
101        Olivia       222    789
102       William       223    465
103        Sophia       224    674
104      Isabella       225    564

# Task-2)

## Assume that you have some data of customers with Cust_ID in one sheet of an excel file and some more data with Cust_ID in a second sheet of same excel file. How can you join these data?
### Read data from first sheet of excel file 'Ecommerce_data.xlsx'

In [7]:
#Reading data from excel file
df_cust = pd.read_excel('Ecommerce_data.xlsx', sheet_name=0)
df_cust

  Cust_ID  Age  Gender     City
0  Cust_1   35    Male   Mumbai
1  Cust_2   24  Female  Chennai
2  Cust_3   20  Female    Delhi
3  Cust_4   45    Male  Chennai
4  Cust_5   37    Male   Mumbai
5  Cust_6   40  Female   Mumbai

### Read data from second sheet of excel file

In [8]:
df_order = pd.read_excel('Ecommerce_data.xlsx', sheet_name=1)
df_order

   Ord_ID  Cust_ID  Ord_quantity      Sales Ord_priority
0  Ord_10   Cust_1           4.0  3237.0000       Medium
1  Ord_14   Cust_2           NaN        NaN          NaN
2  Ord_25   Cust_3           2.0   422.7000          Low
3  Ord_29   Cust_4          15.0  4571.7900         High
4  Ord_34   Cust_5           8.0  4233.1500          Low
5  Ord_52   Cust_6           3.0   164.0200         High
6  Ord_71  Cust_11           1.0   147.6400          Low
7  Ord_94   Cust_8           7.0  3410.1575       Medium

## 1. Inner Merge

In [9]:
#Merging dataframe on common customer_ID
pd.merge(df_cust, df_order, on='Cust_ID')
#merges the common data only

  Cust_ID  Age  Gender     City  Ord_ID  Ord_quantity    Sales Ord_priority
0  Cust_1   35    Male   Mumbai  Ord_10           4.0  3237.00       Medium
1  Cust_2   24  Female  Chennai  Ord_14           NaN      NaN          NaN
2  Cust_3   20  Female    Delhi  Ord_25           2.0   422.70          Low
3  Cust_4   45    Male  Chennai  Ord_29          15.0  4571.79         High
4  Cust_5   37    Male   Mumbai  Ord_34           8.0  4233.15          Low
5  Cust_6   40  Female   Mumbai  Ord_52           3.0   164.02         High

## 2. Outer Merge

In [10]:
#Outer merge
pd.merge(df_cust, df_order, on='Cust_ID', how='outer')
#merges every thing frm both the data.

# If we different column names in two data frames and if we want to merge....
# use left_on and right_on parameters of merge function

,Cust_ID,Age,Gender,City,Ord_ID,Ord_quantity,Sales,Ord_priority
0,Cust_1,35.0,Male,Mumbai,Ord_10,4.0,3237.0000,Medium
1,Cust_2,24.0,Female,Chennai,Ord_14,NaN,NaN,NaN
2,Cust_3,20.0,Female,Delhi,Ord_25,2.0,422.7000,Low
3,Cust_4,45.0,Male,Chennai,Ord_29,15.0,4571.7900,High
4,Cust_5,37.0,Male,Mumbai,Ord_34,8.0,4233.1500,Low
5,Cust_6,40.0,Female,Mumbai,Ord_52,3.0,164.0200,High
6,Cust_11,NaN,NaN,NaN,Ord_71,1.0,147.6400,Low
7,Cust_8,NaN,NaN,NaN,Ord_94,7.0,3410.1575,Medium

## 3. Right Merge

In [11]:
#Right merge
pd.merge(df_cust, df_order, on='Cust_ID', how='right')

,Cust_ID,Age,Gender,City,Ord_ID,Ord_quantity,Sales,Ord_priority
0,Cust_1,35.0,Male,Mumbai,Ord_10,4.0,3237.0000,Medium
1,Cust_2,24.0,Female,Chennai,Ord_14,NaN,NaN,NaN
2,Cust_3,20.0,Female,Delhi,Ord_25,2.0,422.7000,Low
3,Cust_4,45.0,Male,Chennai,Ord_29,15.0,4571.7900,High
4,Cust_5,37.0,Male,Mumbai,Ord_34,8.0,4233.1500,Low
5,Cust_6,40.0,Female,Mumbai,Ord_52,3.0,164.0200,High
6,Cust_11,NaN,NaN,NaN,Ord_71,1.0,147.6400,Low
7,Cust_8,NaN,NaN,NaN,Ord_94,7.0,3410.1575,Medium

## 4. Right Merge

In [12]:
#Left merge
pd.merge(df_cust, df_order, on='Cust_ID', how='left')

  Cust_ID  Age  Gender     City  Ord_ID  Ord_quantity    Sales Ord_priority
0  Cust_1   35    Male   Mumbai  Ord_10           4.0  3237.00       Medium
1  Cust_2   24  Female  Chennai  Ord_14           NaN      NaN          NaN
2  Cust_3   20  Female    Delhi  Ord_25           2.0   422.70          Low
3  Cust_4   45    Male  Chennai  Ord_29          15.0  4571.79         High
4  Cust_5   37    Male   Mumbai  Ord_34           8.0  4233.15          Low
5  Cust_6   40  Female   Mumbai  Ord_52           3.0   164.02         High

# Task-3)

## Represent the name of some persons with their date of births in a tabular format.

In [13]:
#from datetime import date                                      # Import function
df = pd.DataFrame({                                            # Define entires
    'name': ['alice','bob','charlie'],
    'date_of_birth': ['10/25/2005','10/29/2002','01/01/2001']
})
df['date_of_birth'] = pd.to_datetime(df['date_of_birth'])      # convert to type datetime
df                                                             # print output

      name date_of_birth
0    alice    2005-10-25
1      bob    2002-10-29
2  charlie    2001-01-01

# Dataset: Insurance Claim
# File name: 'insurance_data_with_day.csv' 
## Read the data from this file and perform the following computations.

# Task-4)

## Find the duplicate rows except their first occurence in the dataset.

In [14]:
#Reading data from csv file
df = pd.read_csv('insurance_data_with_day.csv')
df.head()

,patientid,dayofmonth,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
0,1,19,39,male,23.2,91,Yes,0,No,southeast,1121.87
1,2,8,24,male,30.1,87,No,0,No,southeast,1131.51
2,3,11,27,male,33.3,82,Yes,0,No,southeast,1135.94
3,4,5,37,male,33.7,80,No,0,No,northwest,1136.40
4,5,21,30,male,34.1,100,No,0,No,northwest,1137.01

In [15]:
df.shape

(1340, 11)

In [16]:
df.duplicated(keep=False) #keep=False marks all duplicate row as true

0       False
1       False
2       False
3       False
4       False
        ...
1335    False
1336    False
1337    False
1338    False
1339    False
Length: 1340, dtype: bool

In [17]:
#Retrieve only duplicate rows
#Let's not consider the patientid from dataframe
df1 = df.loc[:,df.columns!='patientid']
#Select all duplicate rows except their first occurence
df_dup = df1[df1.duplicated(keep='first')]
df_dup

,dayofmonth,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
9,1,29,male,37.3,86,Yes,0,No,northwest,1141.45

# Task-5)

## Find the duplicate rows based on the columns of age, gender and blood pressure.

In [18]:
# Find duplicated rows based on given columns except their first occurence
df_dup1 = df1[df1.duplicated(['age','gender','bloodpressure'], keep='first')]
df_dup1

,dayofmonth,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
9,1,29,male,37.3,86,Yes,0,No,northwest,1141.45
48,23,34,male,16.0,83,No,0,No,northeast,1694.80
60,25,49,male,35.2,80,Yes,1,No,southeast,1727.54
83,3,43,male,36.9,91,Yes,0,No,northwest,1917.32
84,8,36,male,22.0,88,Yes,1,No,southwest,1964.78
...,...,...,...,...,...,...,...,...,...,...
1309,13,47,female,43.9,104,No,2,Yes,southeast,46200.99
1314,23,22,male,33.9,97,No,0,Yes,southeast,46889.26
1319,10,40,male,36.3,94,Yes,1,Yes,southwest,47403.88
1335,27,44,female,35.5,88,Yes,0,Yes,northwest,55135.40
1337,27,30,male,34.5,91,Yes,3,Yes,northwest,60021.40

In [19]:
# Keep=False will select all duplicate rows
df_dup1 = df1[df1.duplicated(['age','gender','bloodpressure'], keep=False)]
df_dup1

,dayofmonth,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
0,19,39,male,23.2,91,Yes,0,No,southeast,1121.87
2,11,27,male,33.3,82,Yes,0,No,southeast,1135.94
4,21,30,male,34.1,100,No,0,No,northwest,1137.01
5,16,47,male,34.4,96,Yes,0,No,northwest,1137.47
6,1,29,male,37.3,86,Yes,0,No,northwest,1141.45
...,...,...,...,...,...,...,...,...,...,...
1309,13,47,female,43.9,104,No,2,Yes,southeast,46200.99
1314,23,22,male,33.9,97,No,0,Yes,southeast,46889.26
1319,10,40,male,36.3,94,Yes,1,Yes,southwest,47403.88
1335,27,44,female,35.5,88,Yes,0,Yes,northwest,55135.40
1337,27,30,male,34.5,91,Yes,3,Yes,northwest,60021.40

# Task-6)

## Drop the duplicate rows where column matches.

In [20]:
print(df1.shape)
df_drop_duplicate = df1.drop_duplicates()
print(df_drop_duplicate.shape)

(1340, 10)
(1339, 10)

# Task-7)

## Drop the duplicate rows except their first occurence based on the columns of age, gender, bmi and children.

In [21]:
print(df1.shape)
#Finding duplicate rows based on the columns of 'age','gender','bmi','children'
df_duplicate_by_col = df1[df1.duplicated(['age','gender','bmi','children'], keep=False)]
df_duplicate_by_col.shape

(1340, 10)

(31, 10)

In [22]:
df_duplicate_by = df_duplicate_by_col.drop_duplicates(subset=['age','gender','bmi','children'], keep='first')
df_duplicate_by

,dayofmonth,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
6,1,29,male,37.3,86,Yes,0,No,northwest,1141.45
20,13,45,male,23.2,85,Yes,0,No,southeast,1515.34
56,15,23,male,28.5,88,Yes,0,No,northwest,1712.23
98,26,47,male,32.1,81,No,0,No,northwest,2055.32
108,15,26,female,37.4,83,Yes,0,No,northwest,2138.07
117,27,59,female,24.1,82,No,1,No,southeast,2201.10
161,29,21,male,31.4,91,No,1,No,northwest,2643.27
165,9,30,male,31.1,91,No,0,No,northwest,2699.57
245,19,23,male,31.4,88,No,1,No,southwest,3659.35
325,5,31,female,30.2,83,No,3,No,northwest,4618.08
377,1,57,female,34.8,96,No,1,No,southwest,5246.05
454,9,24,male,32.3,92,Yes,2,No,southeast,6338.08
656,30,46,male,31.6,91,No,0,No,northwest,9174.14
1011,19,32,female,26.8,109,No,1,Yes,southeast,17085.27
1321,25,26,male,37.0,81,No,2,Yes,northwest,47496.49

In [23]:
s = df_duplicate_by.index
s

Int64Index([6, 20, 56, 98, 108, 117, 161, 165, 245, 325, 377, 454, 656, 1011,
            1321],
           dtype='int64')

In [24]:
print("Now you can delete the rows with index value ", df_duplicate_by.index,"from the original dataframe")

Now you can delete the rows with index value  Int64Index([6, 20, 56, 98, 108, 117, 161, 165, 245, 325, 377, 454, 656, 1011,
            1321],
           dtype='int64') from the original dataframe

In [25]:
df = df.drop(labels=s, axis=0)
df

,patientid,dayofmonth,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
0,1,19,39,male,23.2,91,Yes,0,No,southeast,1121.87
1,2,8,24,male,30.1,87,No,0,No,southeast,1131.51
2,3,11,27,male,33.3,82,Yes,0,No,southeast,1135.94
3,4,5,37,male,33.7,80,No,0,No,northwest,1136.40
4,5,21,30,male,34.1,100,No,0,No,northwest,1137.01
...,...,...,...,...,...,...,...,...,...,...,...
1335,1336,27,44,female,35.5,88,Yes,0,Yes,northwest,55135.40
1336,1337,15,59,female,38.1,120,No,1,Yes,northeast,58571.07
1337,1338,27,30,male,34.5,91,Yes,3,Yes,northwest,60021.40
1338,1339,15,37,male,30.4,106,No,0,Yes,southeast,62592.87
1339,1340,10,30,female,47.4,101,No,0,Yes,southeast,63770.43

In [26]:
df.shape

(1325, 11)

# Task-8)

## Drop odd number rows from 401 to 420. Also drop the column 'dayofmonth'.
### First, drop odd number rows.

In [27]:
df = df.drop(labels=[401,403,405,407,409,411,413,415,417,419], axis=0)
df

,patientid,dayofmonth,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
0,1,19,39,male,23.2,91,Yes,0,No,southeast,1121.87
1,2,8,24,male,30.1,87,No,0,No,southeast,1131.51
2,3,11,27,male,33.3,82,Yes,0,No,southeast,1135.94
3,4,5,37,male,33.7,80,No,0,No,northwest,1136.40
4,5,21,30,male,34.1,100,No,0,No,northwest,1137.01
...,...,...,...,...,...,...,...,...,...,...,...
1335,1336,27,44,female,35.5,88,Yes,0,Yes,northwest,55135.40
1336,1337,15,59,female,38.1,120,No,1,Yes,northeast,58571.07
1337,1338,27,30,male,34.5,91,Yes,3,Yes,northwest,60021.40
1338,1339,15,37,male,30.4,106,No,0,Yes,southeast,62592.87
1339,1340,10,30,female,47.4,101,No,0,Yes,southeast,63770.43

### Then, drop the column 'dayofmonth'.

In [28]:
#Dropping the column dayofmonth
df = df.drop('dayofmonth', axis=1)
df.head()

,patientid,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
0,1,39,male,23.2,91,Yes,0,No,southeast,1121.87
1,2,24,male,30.1,87,No,0,No,southeast,1131.51
2,3,27,male,33.3,82,Yes,0,No,southeast,1135.94
3,4,37,male,33.7,80,No,0,No,northwest,1136.40
4,5,30,male,34.1,100,No,0,No,northwest,1137.01

# Task-9)

## Replace the values southeast, southwest, northeast and northwest by South_East, South_West, North_East and North_West respectively.

In [29]:
#to display full/all data [not the first five .......last five]
pd.set_option('display.max_rows',None)

In [30]:
df = df.replace(to_replace=['southeast', 'southwest', 'northeast','northwest'], value=['South_East', 'South_West', 'North_East', 'North_West'])
df

,patientid,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
0,1,39,male,23.2,91,Yes,0,No,South_East,1121.87
1,2,24,male,30.1,87,No,0,No,South_East,1131.51
2,3,27,male,33.3,82,Yes,0,No,South_East,1135.94
3,4,37,male,33.7,80,No,0,No,North_West,1136.40
4,5,30,male,34.1,100,No,0,No,North_West,1137.01
5,6,47,male,34.4,96,Yes,0,No,North_West,1137.47
7,8,19,male,41.1,100,No,0,No,North_West,1146.80
8,9,20,male,43.0,86,No,0,No,North_West,1149.40
9,10,29,male,37.3,86,Yes,0,No,North_West,1141.45
10,11,36,male,19.8,88,Yes,0,No,North_West,1241.57
11,12,37,male,20.3,90,Yes,0,No,North_West,1242.26
12,13,19,male,20.7,81,NaN,0,No,North_West,1242.82
13,14,32,male,27.6,100,No,0,No,South_West,1252.41
14,15,40,male,28.7,81,Yes,0,No,South_West,1253.94
15,16,32,male,30.4,86,Yes,0,No,South_West,1256.30
16,17,35,male,34.1,90,No,0,No,South_West,1261.44
17,18,41,male,34.4,84,No,0,No,South_West,1261.86
18,19,49,male,35.4,97,Yes,0,No,South_West,1263.25
19,20,48,male,33.3,91,Yes,0,No,South_East,1391.53
21,22,34,male,31.1,96,No,0,No,South_West,1526.31
22,23,18,male,35.5,100,Yes,0,No,South_East,1532.47
23,24,42,male,36.9,93,No,0,No,South_East,1534.30
24,25,50,female,20.8,85,Yes,0,No,South_East,1607.51
25,26,23,male,43.0,86,No,0,No,North_West,1149.40
26,27,36,female,26.7,97,Yes,0,No,South_East,1615.77
27,28,30,male,17.5,93,Yes,0,No,North_West,1621.34
28,29,58,female,31.1,87,No,0,No,South_East,1621.88
29,30,35,female,31.4,93,No,0,No,South_East,1622.19
30,31,29,male,20.4,80,Yes,0,No,North_West,1625.43
31,32,49,male,21.8,80,No,0,No,North_West,1627.28
32,33,21,male,22.6,96,Yes,0,No,North_West,1628.47
33,34,52,female,36.9,81,No,0,No,South_East,1629.83
34,35,43,female,38.2,86,Yes,0,No,South_East,1631.67
35,36,47,female,38.3,93,No,0,No,South_East,1631.82
36,37,48,male,25.2,98,No,0,No,North_West,1632.04
37,38,34,male,25.6,83,No,0,No,North_West,1632.56
38,39,28,female,39.2,87,No,0,No,South_East,1633.04
39,40,49,female,39.8,100,Yes,0,No,South_East,1633.96
40,41,29,female,40.3,94,No,0,No,South_East,1634.57
41,42,18,male,27.8,93,No,0,No,North_West,1635.73
42,43,32,male,30.6,93,No,0,No,North_West,1639.56
43,44,44,male,30.6,82,No,0,No,North_West,1639.56
44,45,37,male,35.5,91,No,0,No,North_West,1646.43
45,46,29,male,26.8,94,Yes,0,No,South_East,1665.00
46,47,24,male,33.8,89,No,0,No,South_East,1674.63
47,48,31,male,39.5,80,Yes,0,No,South_West,1682.60
48,49,34,male,16.0,83,No,0,No,North_East,1694.80
49,50,30,male,21.5,83,Yes,0,No,North_East,1702.46
50,51,45,male,23.0,81,Yes,0,No,North_East,1704.57
51,52,31,male,23.1,81,Yes,0,No,North_West,1704.70
52,53,30,male,23.8,91,Yes,0,No,North_West,1705.62
53,54,34,male,25.5,82,Yes,0,No,North_West,1708.00
54,55,21,male,26.1,87,Yes,0,No,North_West,1708.93
55,56,21,male,23.3,80,Yes,1,No,North_West,1711.03
57,58,32,male,29.4,97,No,1,No,South_East,1719.44
58,59,50,male,30.0,88,No,1,No,South_East,1720.35
59,60,47,male,33.8,90,No,1,No,South_East,1725.55
60,61,49,male,35.2,80,Yes,1,No,South_East,1727.54
61,62,32,female,17.8,90,No,0,No,South_West,1727.79
62,63,51,female,18.6,98,Yes,0,No,South_West,1728.90
63,64,60,female,20.6,90,No,0,No,South_West,1731.68
64,65,32,female,24.7,89,No,0,No,South_West,1737.38
65,66,51,female,28.9,87,Yes,0,No,South_West,1743.21
66,67,27,female,29.8,100,No,0,No,South_West,1744.47
67,68,39,female,32.9,99,Yes,0,No,South_West,1748.77
68,69,26,female,40.5,87,Yes,0,No,South_West,1759.34
69,70,32,male,29.7,80,Yes,0,No,North_West,1769.53
70,71,28,male,26.5,88,Yes,0,No,South_East,1815.88
71,72,48,male,32.6,80,Yes,0,No,South_East,1824.29
72,73,22,male,34.4,98,Yes,0,No,South_West,1826.84
73,74,20,male,20.9,98,No,1,No,South_West,1832.09
74,75,50,male,24.6,90,No,1,No,South_West,1837.24
75,76,30,male,41.9,95,Yes,0,No,South_East,1837.28
76,77,38,male,28.4,87,No,1,No,South_West,1842.52
77,78,50,female,29.6,95,No,0,No,South_West,1875.34
78,79,42,female,31.5,100,No,0,No,South_East,1877.93
79,80,53,female,33.0,83,Yes,0,No,South_East,1880.07
80,81,26,female,33.3,83,Yes,0,No,South_West,1880.49
81,82,43,male,29.0,91,Yes,0,No,North_West,1906.36
82,83,42,male,31.3,98,No,0,No,North_West,1909.53
83,84,43,male,36.9,91,Yes,0,No,North_West,1917.32
84,85,36,male,22.0,88,Yes,1,No,South_West,1964.78
85,86,19,male,27.9,94,Yes,0,No,North_East,1967.02
86,87,19,male,23.4,97,No,0,No,North_West,1969.61
87,88,37,male,25.8,86,No,0,No,North_West,1972.95
88,89,40,male,29.3,97,Yes,0,No,North_West,1977.82
89,90,23,male,33.0,80,Yes,1,No,North_West,1980.07
90,91,19,male,32.0,100,Yes,0,No,South_East,1981.58
91,92,20,male,40.5,95,No,0,No,South_East,1984.45
92,93,41,male,35.9,97,No,0,No,South_East,1986.93
93,94,26,female,25.8,100,Yes,0,No,South_West,2007.95
94,95,48,female,34.6,99,No,0,No,South_West,2020.18
95,96,54,female,34.9,90,No,0,No,South_East,2020.55
96,97,44,female,39.5,93,Yes,0,No,South_East,2026.97
97,98,44,male,25.2,91,No,0,No,North_West,2045.69
99,100,50,male,26.0,82,No,0,No,North_East,2102.26
100,101,30,male,22.3,83,Yes,1,No,South_West,2103.08
101,102,33,male,27.4,100,No,0,No,North_East,2104.11
102,103,59,female,22.5,87,No,0,No,North_West,2117.34
103,104,42,female,30.5,99,No,0,No,North_West,2128.43
104,105,52,female,32.1,94,Yes,0,No,North_West,2130.68
105,106,43,female,35.2,80,No,0,No,North_West,2134.90
106,107,42,female,36.6,90,No,0,No,North_West,2136.88
107,108,33,male,25.7,100,Yes,0,No,South_East,2137.65
109,110,41,female,24.3,91,Yes,0,No,South_West,2150.47
110,111,27,female,27.1,88,Yes,0,No,South_West,2154.36
111,112,37,female,28.1,80,No,0,No,South_East,2155.68
112,113,43,female,28.8,88,Yes,0,No,South_East,2156.75
113,114,30,female,36.0,80,No,0,No,South_West,2166.73
114,115,47,female,25.1,80,No,0,No,South_East,2196.47
115,116,26,female,26.3,87,Yes,0,No,South_East,2198.19
116,117,49,female,28.2,98,Yes,0,No,South_East,2200.83
118,119,58,female,30.1,81,Yes,0,No,South_East,2203.47
119,120,32,female,30.3,94,Yes,0,No,South_East,2203.74
120,121,37,female,31.9,89,No,0,No,South_East,2205.98
121,122,48,female,33.2,97,No,0,No,South_East,2207.70
122,123,52,female,35.6,89,No,0,No,South_East,2211.13
123,124,55,female,40.2,82,No,0,No,South_East,2217.47
124,125,33,female,40.3,94,Yes,0,No,South_East,2217.60
125,126,53,female,37.3,88,Yes,1,No,South_East,2219.45
126,127,26,male,25.6,86,No,1,No,North_West,2221.56
127,128,49,male,28.9,81,No,0,No,North_West,2250.84
128,129,31,male,31.7,90,No,0,No,North_West,2254.80
129,130,42,female,29.0,81,Yes,0,No,North_West,2257.48
130,131,30,female,31.9,89,No,0,No,North_West,2261.57
131,132,45,male,20.8,88,No,0,No,North_West,2302.30
132,133,49,male,26.2,91,No,2,No,South_East,2304.00
133,134,47,male,35.4,95,No,0,No,South_East,2322.62
134,135,47,female,28.4,87,Yes,1,No,South_West,2331.52
135,136,29,male,23.7,89,Yes,0,No,North_West,2352.97
136,137,40,male,32.4,81,No,1,No,North_West,2362.23
137,138,21,male,23.8,95,Yes,0,No,South_East,2395.17
138,139,32,male,24.5,90,Yes,0,No,South_East,2396.10
139,140,26,female,35.7,90,Yes,0,No,North_West,2404.73
140,141,47,male,35.2,80,No,1,No,South_West,2416.96
141,142,46,male,50.4,89,Yes,1,No,South_East,2438.06
142,143,44,female,28.8,94,Yes,0,No,South_East,2457.21
143,144,41,female,22.6,91,Yes,0,No,South_West,2457.50
144,145,37,female,30.6,96,Yes,0,No,South_East,2459.72
145,146,29,female,27.7,80,Yes,0,No,South_East,2464.62
146,147,47,female,34.0,84,No,0,No,South_East,2473.33
147,148,35,female,39.5,82,Yes,0,No,South_East,2480.98
148,149,48,male,23.1,91,Yes,0,No,South_East,2483.74
149,150,22,male,30.5,82,No,0,No,South_West,2494.02
150,151,41,male,32.7,93,No,0,No,South_East,2497.04
151,152,26,male,33.7,99,No,0,No,South_East,2498.41
152,153,18,male,27.6,94,Yes,0,No,North_West,2523.17
153,154,28,female,20.2,82,No,0,No,North_West,2527.82
154,155,33,male,35.6,98,No,0,No,North_West,2534.39
155,156,49,male,31.1,88,Yes,2,No,South_East,2566.47
156,157,33,female,17.4,87,No,1,No,South_West,2585.27
157,158,43,female,22.1,82,Yes,0,No,South_East,2585.85
158,159,57,female,26.4,86,No,1,No,South_West,2597.78
159,160,30,female,30.3,94,Yes,0,No,South_West,2632.99
160,161,42,male,28.3,86,Yes,1,No,North_West,2639.04
162,163,47,male,17.7,92,Yes,0,No,North_West,2680.95
163,164,28,male,38.1,81,Yes,0,No,South_East,2689.50
164,165,52,female,28.1,90,Yes,0,No,North_West,2690.11
166,167,51,female,24.5,80,Yes,1,No,North_West,2709.11
167,168,58,female,24.6,87,Yes,1,No,North_West,2709.24
168,169,26,female,25.7,88,No,1,No,North_West,2710.83
169,170,41,female,31.8,88,Yes,1,No,North_West,2719.28
170,171,46,male,26.2,84,No,0,No,South_East,2721.32
171,172,23,male,30.6,96,No,0,No,South_East,2727.40
172,173,34,female,39.6,91,Yes,1,No,North_West,2730.11
173,174,29,female,23.2,80,No,0,No,South_East,2731.91
174,175,58,female,30.4,85,Yes,0,No,South_East,2741.95
175,176,59,female,39.8,81,Yes,0,No,North_East,2755.02
176,177,30,male,17.4,89,No,1,No,North_West,2775.19
177,178,49,male,27.4,91,No,1,No,North_West,2789.06
178,179,60,female,32.1,98,No,2,No,South_East,2801.26
179,180,49,male,20.6,92,No,2,No,North_West,2803.70
180,181,45,female,24.2,88,No,0,No,North_West,2842.76
181,182,54,female,29.9,90,No,0,No,North_West,2850.68
182,183,27,female,33.3,92,Yes,0,No,North_West,2855.44
183,184,37,male,27.2,87,Yes,0,No,South_West,2866.09
184,185,48,male,27.9,82,Yes,0,No,South_East,2867.12
185,186,49,male,29.5,92,No,0,No,North_East,2897.32
186,187,25,female,34.9,100,No,0,No,North_East,2899.49
187,188,20,male,29.2,95,No,1,No,South_East,2902.91
188,189,35,male,30.0,86,No,1,No,South_West,2904.09
189,190,37,female,23.4,96,No,2,No,South_West,2913.57
190,191,28,male,46.5,94,No,1,No,South_East,2927.06
191,192,28,female,24.1,80,No,0,No,South_West,2974.13
192,193,55,female,34.5,87,Yes,0,No,North_West,3021.81
193,194,54,female,25.3,100,No,0,No,North_East,3044.21
194,195,57,female,26.6,83,No,0,No,North_East,3046.06
195,196,33,female,31.8,98,Yes,2,No,South_East,3056.39
196,197,30,male,30.9,89,Yes,0,No,North_West,3062.51
197,198,49,male,26.0,98,Yes,0,No,North_East,3070.81
198,199,25,male,23.0,81,Yes,0,No,North_East,1704.57
199,200,38,male,23.8,99,Yes,2,No,North_West,3077.10
200,201,60,female,25.8,100,Yes,0,No,South_West,3161.45
201,202,59,female,16.8,96,Yes,1,No,North_East,3167.46
202,203,52,female,33.1,87,No,0,No,South_East,3171.61
203,204,35,female,33.4,99,No,0,No,South_West,3172.02
204,205,35,female,22.2,93,No,0,No,North_West,3176.29
205,206,48,female,22.6,94,No,0,No,North_West,3176.82
206,207,27,female,21.9,80,No,2,No,South_East,3180.51
207,208,48,female,40.2,82,No,0,No,North_West,3201.25
208,209,45,female,23.5,96,No,0,No,North_East,3206.49
209,210,33,female,20.8,87,Yes,1,No,South_West,3208.79
210,211,59,female,28.6,82,No,0,No,North_East,3213.62
211,212,36,female,34.0,88,Yes,1,No,South_East,3227.12
212,213,46,female,42.1,89,No,1,No,South_East,3238.44
213,214,35,male,20.4,88,No,0,No,South_West,3260.20
214,215,43,male,35.4,86,Yes,0,No,North_East,3268.85
215,216,28,male,37.1,90,Yes,1,No,South_West,3277.16
216,217,26,male,25.7,91,No,2,No,North_East,3279.87
217,218,23,male,33.9,81,No,1,No,North_West,3292.53
218,219,48,male,25.8,82,Yes,1,No,North_East,3309.79
219,220,49,female,25.9,97,No,0,No,South_West,3353.28
220,221,41,female,21.5,92,No,0,No,North_West,3353.47
221,222,28,female,35.5,95,Yes,0,No,South_East,3366.67
222,223,53,female,19.8,93,Yes,1,No,South_West,3378.91
223,224,28,female,28.8,99,Yes,0,No,North_East,3385.40
224,225,40,female,29.5,100,No,1,No,South_East,3392.37
225,226,60,female,29.9,82,Yes,1,No,South_East,3392.98
226,227,35,female,38.7,85,No,2,No,South_East,3393.36
227,228,34,female,42.4,92,No,1,No,South_West,3410.32
228,229,40,male,34.8,81,No,3,No,South_West,3443.06
229,230,42,male,38.9,94,No,1,No,South_East,3471.41
230,231,22,male,30.4,95,Yes,3,No,South_East,3481.87
231,232,35,male,23.7,88,No,2,No,South_West,3484.33
232,233,49,male,32.5,93,Yes,1,No,South_East,3490.55
233,234,30,female,39.3,92,No,2,No,South_East,3500.61
234,235,21,male,28.5,98,Yes,2,No,North_West,3537.70
235,236,58,female,27.7,82,No,0,No,South_West,3554.20
236,237,59,female,34.8,85,Yes,0,No,North_West,3556.92
237,238,48,female,25.2,82,No,0,No,South_East,3558.62
238,239,32,female,23.2,89,Yes,1,No,South_East,3561.89
239,240,31,female,34.8,88,No,1,No,South_West,3578.00
240,241,47,female,33.6,84,Yes,2,No,North_West,3579.83
241,242,23,male,32.7,82,Yes,3,No,South_West,3591.48
242,243,36,female,22.5,91,Yes,1,No,North_West,3594.17
243,244,48,male,37.1,97,No,3,No,South_West,3597.60
244,245,18,male,25.5,99,Yes,0,No,North_East,3645.09
246,247,20,male,45.9,97,No,2,No,South_West,3693.43
247,248,31,male,30.3,92,No,0,No,South_East,3704.35
248,249,35,female,17.3,82,Yes,0,No,North_East,3732.63
249,250,49,female,26.0,88,No,0,No,North_West,3736.46
250,251,45,female,25.7,80,No,0,No,South_East,3756.62
251,252,30,female,26.6,89,Yes,0,No,South_East,3757.84
252,253,52,female,29.1,90,No,0,No,South_West,3761.29
253,254,44,female,37.6,84,No,1,No,South_East,3766.88
254,255,31,male,23.8,83,No,2,No,South_West,3847.67
255,256,25,male,30.9,86,Yes,0,No,North_East,3857.76
256,257,34,male,20.2,80,No,3,No,North_East,3861.21
257,258,33,male,28.9,87,No,0,No,North_West,3866.86
258,259,32,male,39.5,88,Yes,1,No,South_East,3875.73
259,260,18,male,30.9,92,No,2,No,North_West,3877.30
260,261,28,male,26.8,92,No,3,No,South_West,3906.13
261,262,42,female,34.6,80,No,2,No,North_East,3925.76
262,263,36,male,34.2,96,Yes,0,No,South_East,3935.18
263,264,46,female,31.2,88,Yes,0,No,North_East,3943.60
264,265,46,female,29.6,86,Yes,1,No,South_East,3947.41
265,266,38,female,31.3,86,Yes,1,No,North_West,3956.07
266,267,53,female,28.9,93,No,0,No,South_East,3972.92
267,268,35,female,29.9,93,Yes,2,No,South_East,3981.98
268,269,48,female,34.2,99,Yes,2,No,South_West,3987.93
269,270,49,female,41.1,88,Yes,0,No,South_West,3989.84
270,271,46,female,44.2,91,Yes,0,No,South_East,3994.18
271,272,48,male,20.0,82,No,3,No,North_East,4005.42
272,273,44,male,24.1,86,No,1,No,North_West,4032.24
273,274,43,male,29.0,91,No,1,No,North_East,4040.56
274,275,24,male,37.3,99,Yes,2,No,South_East,4058.12
275,276,37,male,33.2,90,Yes,2,No,North_West,4058.71
276,277,23,male,30.0,95,Yes,1,No,South_East,4074.45
277,278,26,male,31.5,95,Yes,1,No,South_West,4076.50
278,279,49,female,25.9,80,Yes,1,No,North_West,4133.64
279,280,47,female,21.8,98,No,0,No,North_West,4134.08
280,281,25,female,27.9,88,Yes,0,No,South_East,4137.52
281,282,59,female,32.4,94,No,1,No,South_West,4149.74
282,283,48,female,33.3,100,Yes,1,No,South_East,4151.03
283,284,34,female,24.3,90,Yes,0,No,South_East,4185.10
284,285,25,female,26.8,98,No,2,No,North_West,4189.11
285,286,27,female,30.1,81,No,3,No,South_West,4234.93
286,287,30,male,27.6,90,No,1,No,South_East,4237.13
287,288,35,male,25.9,84,Yes,1,No,North_West,4239.89
288,289,37,male,28.6,93,Yes,1,No,North_West,4243.59
289,290,35,male,30.3,80,No,3,No,South_West,4260.74
290,291,49,male,44.2,80,No,2,No,South_East,4266.17
291,292,25,female,21.3,95,Yes,3,No,North_West,4296.27
292,293,21,male,35.8,88,No,0,No,North_West,4320.41
293,294,37,female,28.9,87,No,1,No,South_East,4337.74
294,295,57,female,26.5,90,NaN,2,No,South_East,4340.44
295,296,32,female,31.1,88,No,0,No,South_East,4347.02
296,297,25,female,33.0,89,Yes,2,No,South_East,4349.46
297,298,40,female,29.3,87,Yes,1,No,South_East,4350.51
298,299,30,female,29.7,93,No,0,No,North_West,4357.04
299,300,31,female,24.3,90,Yes,3,No,South_West,4391.65
300,301,37,male,29.7,81,No,0,No,South_East,4399.73
301,302,26,male,31.5,88,Yes,0,No,South_West,4402.23
302,303,41,female,27.7,92,Yes,0,No,South_East,4415.16
303,304,46,male,22.5,88,Yes,2,No,South_East,4428.89
304,305,32,male,31.7,83,Yes,2,No,North_West,4433.39
305,306,34,male,32.1,83,Yes,2,No,North_West,4433.92
306,307,44,male,27.0,100,Yes,2,No,South_East,4435.09
307,308,46,male,29.3,80,Yes,2,No,South_East,4438.26
308,309,41,male,26.9,90,No,1,No,South_East,4441.21
309,310,32,male,33.0,94,Yes,3,No,South_East,4449.46
310,311,43,male,27.8,81,No,1,No,North_West,4454.40
311,312,37,male,33.8,90,No,1,No,North_West,4462.72
312,313,21,male,38.4,87,Yes,2,No,South_East,4463.21
313,314,45,female,35.0,91,Yes,3,No,North_West,4466.62
314,315,36,male,21.4,89,No,0,No,South_East,4500.34
315,316,44,male,33.7,96,No,4,No,South_East,4504.66
316,317,35,male,34.7,83,Yes,0,No,South_East,4518.83
317,318,51,female,28.4,93,No,1,No,North_West,4527.18
318,319,47,female,24.6,90,Yes,2,No,South_West,4529.48
319,320,26,male,42.9,95,Yes,1,No,South_West,4536.26
320,321,50,female,20.5,89,Yes,0,No,South_East,4544.23
321,322,43,female,31.4,99,No,4,No,South_East,4561.19
322,323,55,female,29.6,93,Yes,1,No,South_East,4562.84
323,324,26,female,29.4,96,Yes,2,No,South_East,4564.19
324,325,60,female,26.7,94,No,0,No,North_West,4571.41
326,327,18,male,30.8,97,Yes,0,No,South_West,4646.76
327,328,47,male,27.3,85,Yes,3,No,South_East,4661.29
328,329,26,male,37.3,86,Yes,1,No,South_East,4667.61
329,330,22,male,35.2,87,Yes,2,No,South_West,4670.64
330,331,32,male,37.2,82,No,2,No,South_East,4673.39
331,332,43,male,46.5,83,Yes,2,No,South_East,4686.39
332,333,46,female,28.6,80,No,5,No,South_West,4687.80
333,334,56,female,21.9,100,Yes,1,No,South_East,4718.20
334,335,45,female,22.9,94,No,1,No,South_East,4719.52
335,336,42,female,23.8,80,Yes,2,No,North_West,4719.74
336,337,48,female,32.7,95,No,1,No,North_West,4738.27
337,338,29,male,27.1,82,Yes,1,No,South_West,4746.34
338,339,44,male,27.6,86,No,1,No,South_East,4747.05
339,340,19,male,30.5,92,Yes,1,No,South_West,4751.07
340,341,50,female,43.1,98,No,2,No,South_East,4753.64
341,342,46,male,38.6,83,Yes,1,No,South_West,4762.33
342,343,33,female,18.5,94,Yes,1,No,South_West,4766.02
343,344,56,female,28.3,100,Yes,1,No,South_East,4779.60
344,345,38,female,39.8,85,Yes,1,No,South_East,4795.66
345,346,33,male,18.9,87,Yes,3,No,South_East,4827.90
346,347,55,female,37.0,83,Yes,5,No,South_West,4830.63
347,348,43,male,31.6,89,No,3,No,South_East,4837.58
348,349,46,male,32.6,82,Yes,3,No,South_East,4846.92
349,350,47,male,26.7,93,No,4,No,North_West,4877.98
350,351,60,female,26.2,99,No,0,No,South_West,4883.87
351,352,31,female,29.9,85,No,0,No,South_East,4889.04
352,353,28,male,35.8,97,No,2,No,South_East,4890.00
353,354,39,male,25.3,91,No,1,No,North_West,4894.75
354,355,48,female,20.2,97,No,2,No,North_West,4906.41
355,356,38,male,30.1,87,No,5,No,South_East,4915.06
356,357,40,female,32.1,95,Yes,2,No,North_West,4922.92
357,358,31,female,23.6,95,No,2,No,South_West,4931.65
358,359,25,female,25.8,97,Yes,2,No,South_West,4934.71
359,360,46,female,36.6,84,Yes,2,No,South_East,4949.76
360,361,29,female,23.6,87,Yes,0,No,South_East,4992.38
361,362,27,female,26.7,99,No,1,No,South_East,5002.78
362,363,40,female,27.5,98,Yes,1,No,South_West,5003.85
363,364,25,female,33.7,95,No,1,No,South_West,5012.47
364,365,35,male,29.6,94,Yes,0,No,North_West,5028.15
365,366,35,male,27.6,100,No,2,No,South_East,5031.27
366,367,24,male,23.9,84,No,5,No,South_West,5080.10
367,368,19,male,17.9,90,No,1,No,North_West,5116.50
368,369,39,male,42.1,100,No,2,No,South_East,5124.19
369,370,31,male,24.1,88,Yes,1,No,North_West,5125.22
370,371,55,female,38.8,86,No,3,No,South_East,5138.26
371,372,33,female,31.5,86,No,1,No,South_East,5148.55
372,373,34,female,29.8,100,Yes,2,No,South_West,5152.13
373,374,32,male,22.5,93,No,3,No,South_East,5209.58
374,375,38,female,26.1,81,Yes,0,No,South_East,5227.99
375,376,46,female,31.0,84,No,1,No,South_West,5240.77
376,377,57,female,34.2,93,Yes,1,No,South_East,5245.23
378,379,23,male,30.8,89,Yes,3,No,South_West,5253.52
379,380,20,male,24.6,92,No,2,No,North_West,5257.51
380,381,19,male,27.5,83,No,2,No,North_West,5261.47
381,382,44,female,25.8,90,No,0,No,North_West,5266.37
382,383,52,female,26.9,96,No,0,No,North_West,5267.82
383,384,32,female,30.0,88,Yes,0,No,North_West,5272.18
384,385,41,female,26.3,82,Yes,3,No,North_West,5312.17
385,386,49,female,30.9,90,Yes,3,No,South_West,5325.65
386,387,25,female,32.8,81,No,2,No,North_West,5327.40
387,388,31,female,22.1,97,Yes,1,No,South_East,5354.07
388,389,32,male,30.9,91,No,1,No,North_West,5373.36
389,390,54,female,32.9,91,Yes,2,No,South_West,5375.04
390,391,44,male,33.8,96,No,1,No,North_West,5377.46
391,392,40,female,27.6,92,Yes,0,No,South_West,5383.54
392,393,58,female,26.4,88,Yes,1,No,North_West,5385.34
393,394,32,female,37.7,96,No,0,No,South_East,5397.62

# Task-10)

## Add a new column 'High_bmi' after the column 'bmi' and follow the conditions below. 
### (1) In 'bmi', if the value is less than or equal to 32, then assign value 'No' to 'High_bmi'.  
### (2) In 'bmi', if the value is more than 32, then assign value 'Yes' to 'High_bmi'.

In [31]:
import numpy as np
df.insert(4, 'High_bmi',np.nan)
df.head()

,patientid,age,gender,bmi,High_bmi,bloodpressure,diabetic,children,smoker,region,claim
0,1,39,male,23.2,NaN,91,Yes,0,No,South_East,1121.87
1,2,24,male,30.1,NaN,87,No,0,No,South_East,1131.51
2,3,27,male,33.3,NaN,82,Yes,0,No,South_East,1135.94
3,4,37,male,33.7,NaN,80,No,0,No,North_West,1136.40
4,5,30,male,34.1,NaN,100,No,0,No,North_West,1137.01

In [32]:
#Putting the values in the column 'High_bmi' based on given condition
df.loc[df['bmi'] > 32, 'High_bmi'] = 'Yes'
df.loc[df['bmi'] <= 32, 'High_bmi'] = 'No'
df.head()

,patientid,age,gender,bmi,High_bmi,bloodpressure,diabetic,children,smoker,region,claim
0,1,39,male,23.2,No,91,Yes,0,No,South_East,1121.87
1,2,24,male,30.1,No,87,No,0,No,South_East,1131.51
2,3,27,male,33.3,Yes,82,Yes,0,No,South_East,1135.94
3,4,37,male,33.7,Yes,80,No,0,No,North_West,1136.40
4,5,30,male,34.1,Yes,100,No,0,No,North_West,1137.01

# Task-11)

## Group the data based on gender.

In [33]:
gendergroup = df.groupby(['gender'])     # Data based on gender
gendergroup

In [34]:
for x, y in gendergroup:
    print(x)                            # print data based on gender
    print(y)                            # print data based on gender

female
      patientid  age  gender   bmi High_bmi  bloodpressure diabetic  children  \
24           25   50  female  20.8       No             85      Yes         0
26           27   36  female  26.7       No             97      Yes         0
28           29   58  female  31.1       No             87       No         0
29           30   35  female  31.4       No             93       No         0
33           34   52  female  36.9      Yes             81       No         0
34           35   43  female  38.2      Yes             86      Yes         0
35           36   47  female  38.3      Yes             93       No         0
38           39   28  female  39.2      Yes             87       No         0
39           40   49  female  39.8      Yes            100      Yes         0
40           41   29  female  40.3      Yes             94       No         0
61           62   32  female  17.8       No             90       No         0
62           63   51  female  18.6       No             98      Yes         0
63           64   60  female  20.6       No             90       No         0
64           65   32  female  24.7       No             89       No         0
65           66   51  female  28.9       No             87      Yes         0
66           67   27  female  29.8       No            100       No         0
67           68   39  female  32.9      Yes             99      Yes         0
68           69   26  female  40.5      Yes             87      Yes         0
77           78   50  female  29.6       No             95       No         0
78           79   42  female  31.5       No            100       No         0
79           80   53  female  33.0      Yes             83      Yes         0
80           81   26  female  33.3      Yes             83      Yes         0
93           94   26  female  25.8       No            100      Yes         0
94           95   48  female  34.6      Yes             99       No         0
95           96   54  female  34.9      Yes             90       No         0
96           97   44  female  39.5      Yes             93      Yes         0
102         103   59  female  22.5       No             87       No         0
103         104   42  female  30.5       No             99       No         0
104         105   52  female  32.1      Yes             94      Yes         0
105         106   43  female  35.2      Yes             80       No         0
106         107   42  female  36.6      Yes             90       No         0
109         110   41  female  24.3       No             91      Yes         0
110         111   27  female  27.1       No             88      Yes         0
111         112   37  female  28.1       No             80       No         0
112         113   43  female  28.8       No             88      Yes         0
113         114   30  female  36.0      Yes             80       No         0
114         115   47  female  25.1       No             80       No         0
115         116   26  female  26.3       No             87      Yes         0
116         117   49  female  28.2       No             98      Yes         0
118         119   58  female  30.1       No             81      Yes         0
119         120   32  female  30.3       No             94      Yes         0
120         121   37  female  31.9       No             89       No         0
121         122   48  female  33.2      Yes             97       No         0
122         123   52  female  35.6      Yes             89       No         0
123         124   55  female  40.2      Yes             82       No         0
124         125   33  female  40.3      Yes             94      Yes         0
125         126   53  female  37.3      Yes             88      Yes         1
129         130   42  female  29.0       No             81      Yes         0
130         131   30  female  31.9       No             89       No         0
134         135   47  female  28.4       No             87      Yes         1
139         140   26  female  35.7      Yes             90      Yes         0
142         143   44  female  28.8       No             94      Yes         0
143         144   41  female  22.6       No             91      Yes         0
144         145   37  female  30.6       No             96      Yes         0
145         146   29  female  27.7       No             80      Yes         0
146         147   47  female  34.0      Yes             84       No         0
147         148   35  female  39.5      Yes             82      Yes         0
153         154   28  female  20.2       No             82       No         0
156         157   33  female  17.4       No             87       No         1
157         158   43  female  22.1       No             82      Yes         0
158         159   57  female  26.4       No             86       No         1
159         160   30  female  30.3       No             94      Yes         0
164         165   52  female  28.1       No             90      Yes         0
166         167   51  female  24.5       No             80      Yes         1
167         168   58  female  24.6       No             87      Yes         1
168         169   26  female  25.7       No             88       No         1
169         170   41  female  31.8       No             88      Yes         1
172         173   34  female  39.6      Yes             91      Yes         1
173         174   29  female  23.2       No             80       No         0
174         175   58  female  30.4       No             85      Yes         0
175         176   59  female  39.8      Yes             81      Yes         0
178         179   60  female  32.1      Yes             98       No         2
180         181   45  female  24.2       No             88       No         0
181         182   54  female  29.9       No             90       No         0
182         183   27  female  33.3      Yes             92      Yes         0
186         187   25  female  34.9      Yes            100       No         0
189         190   37  female  23.4       No             96       No         2
191         192   28  female  24.1       No             80       No         0
192         193   55  female  34.5      Yes             87      Yes         0
193         194   54  female  25.3       No            100       No         0
194         195   57  female  26.6       No             83       No         0
195         196   33  female  31.8       No             98      Yes         2
200         201   60  female  25.8       No            100      Yes         0
201         202   59  female  16.8       No             96      Yes         1
202         203   52  female  33.1      Yes             87       No         0
203         204   35  female  33.4      Yes             99       No         0
204         205   35  female  22.2       No             93       No         0
205         206   48  female  22.6       No             94       No         0
206         207   27  female  21.9       No             80       No         2
207         208   48  female  40.2      Yes             82       No         0
208         209   45  female  23.5       No             96       No         0
209         210   33  female  20.8       No             87      Yes         1
210         211   59  female  28.6       No             82       No         0
211         212   36  female  34.0      Yes             88      Yes         1
212         213   46  female  42.1      Yes             89       No         1
219         220   49  female  25.9       No             97       No         0
220         221   41  female  21.5       No             92       No         0
221         222   28  female  35.5      Yes             95      Yes         0
222         223   53  female  19.8       No             93      Yes         1
223         224   28  female  28.8       No             99      Yes         0
224         225   40  female  29.5       No            100       No         1
225         226   60  female  29.9       No             82      Yes         1
226         227   35  female  38.7      Yes             85       No         2
227         228   34  female  42.4      Yes             92       No         1
233         234   30  female  39.3      Yes             92       No         2
235         236   58  female  27.7       No             82       No         0
236         237   59  female  34.8      Yes             85      Yes         0
237         238   48  female  25.2       No             82       No         0
238         239   32  female  23.2       No             89      Yes         1
239         240   31  female  34.8      Yes             88       No         1
240         241   47  female  33.6      Yes             84      Yes         2
242         243   36  female  22.5       No             91      Yes         1
248         249   35  female  17.3       No             82      Yes         0
249         250   49  female  26.0       No             88       No         0
250         251   45  female  25.7       No             80       No         0
251         252   30  female  26.6       No             89      Yes         0
252         253   52  female  29.1       No             90       No         0
253         254   44  female  37.6      Yes             84       No         1
261         262   42  female  34.6      Yes             80       No         2
263         264   46  female  31.2       No             88      Yes         0
264         265   46  female  29.6       No             86      Yes         1
265         266   38  female  31.3       No             86      Yes         1
266         267   53  female  28.9       No             93       No         0
267         268   35  female  29.9       No             93      Yes         2
268         269   48  female  34.2      Yes             99      Yes         2
269         270   49  female  41.1      Yes             88      Yes         0
270         271   46  female  44.2      Yes             91      Yes         0
278         279   49  female  25.9       No             80      Yes         1
279         280   47  female  21.8       No             98       No         0
280         281   25  female  27.9       No             88      Yes         0
281         282   59  female  32.4      Yes             94       No         1
282         283   48  female  33.3      Yes            100      Yes         1
283         284   34  female  24.3       No             90      Yes         0
284         285   25  female  26.8       No             98       No         2
285         286   27  female  30.1       No             81       No         3
291         292   25  female  21.3       No             95      Yes         3
293         294   37  female  28.9       No             87       No         1
294         295   57  female  26.5       No             90      NaN         2
295         296   32  female  31.1       No             88       No         0
296         297   25  female  33.0      Yes             89      Yes         2
297         298   40  female  29.3       No             87      Yes         1
298         299   30  female  29.7       No             93       No         0
299         300   31  female  24.3       No             90      Yes         3
302         303   41  female  27.7       No             92      Yes         0
313         314   45  female  35.0      Yes             91      Yes         3
317         318   51  female  28.4       No             93       No         1
318         319   47  female  24.6       No             90      Yes         2
320         321   50  female  20.5       No             89      Yes         0
321         322   43  female  31.4       No             99       No         4
322         323   55  female  29.6       No             93      Yes         1
323         324   26  female  29.4       No             96      Yes         2
324         325   60  female  26.7       No             94       No         0
332         333   46  female  28.6       No             80       No         5
333         334   56  female  21.9       No            100      Yes         1
334         335   45  female  22.9       No             94       No         1
335         336   42  female  23.8       No             80      Yes         2
336         337   48  female  32.7      Yes             95       No         1
340         341   50  female  43.1      Yes             98       No         2
342         343   33  female  18.5       No             94      Yes         1
343         344   56  female  28.3       No            100      Yes         1
344         345   38  female  39.8      Yes             85      Yes         1
346         347   55  female  37.0      Yes             83      Yes         5
350         351   60  female  26.2       No             99       No         0
351         352   31  female  29.9       No             85       No         0
354         355   48  female  20.2       No             97       No         2
356         357   40  female  32.1      Yes             95      Yes         2
357         358   31  female  23.6       No             95       No         2
358         359   25  female  25.8       No             97      Yes         2
359         360   46  female  36.6      Yes             84      Yes         2
360         361   29  female  23.6       No             87      Yes         0
361         362   27  female  26.7       No             99       No         1
362         363   40  female  27.5       No             98      Yes         1
363         364   25  female  33.7      Yes             95       No         1
370         371   55  female  38.8      Yes             86       No         3
371         372   33  female  31.5       No             86       No         1
372         373   34  female  29.8       No            100      Yes         2
374         375   38  female  26.1       No             81      Yes         0
375         376   46  female  31.0       No             84       No         1
376         377   57  female  34.2      Yes             93      Yes         1
381         382   44  female  25.8       No             90       No         0
382         383   52  female  26.9       No             96       No         0
383         384   32  female  30.0       No             88      Yes         0
384         385   41  female  26.3       No             82      Yes         3
385         386   49  female  30.9       No             90      Yes         3
386         387   25  female  32.8      Yes             81       No         2
387         388   31  female  22.1       No             97      Yes         1
389         390   54  female  32.9      Yes             91      Yes         2
391         392   40  female  27.6       No             92      Yes         0
392         393   58  female  26.4       No             88      Yes         1
393         394   32  female  37.7      Yes             96       No         0
394         395   29  female  40.2      Yes             85      Yes         0
399         400   27  female  19.9       No             81       No         0
400         401   57  female  27.7       No             97      Yes         0
402         403   55  female  29.9       No             89       No         1
406         407   43  female  33.3      Yes             94      Yes         1
408         409   57  female  35.8      Yes             85      Yes         1
410         411   25  female  41.8      Yes             95      Yes         0
418         419   28  female  43.3      Yes             90       No         2
420         421   58  female  29.6       No             95      Yes         0
421         422   51  female  36.2      Yes             90      Yes         0
426         427   40  female  38.9      Yes            100      Yes         3
427         428   35  female  28.9       No             97      Yes         1
428         429   34  female  30.7       No             90       No         1
430         431   33  female  37.3      Yes             95      Yes         2
435         436   38  female  34.1      Yes             93       No         1
436         437   28  female  30.5       No             82      Yes         3
439         440   55  female  33.2      Yes             89      Yes         3
440         441   42  female  29.3       No             84       No         3
441         442   39  female  31.0       No             97       No         0
442         443   32  female  31.6       No             91      Yes         0
443         444   32  female  38.0      Yes             92       No         3
446         447   25  female  32.5      Yes            100       No         1
451         452   48  female  29.5       No             95       No         2
452         453   56  female  30.8       No             92      Yes         2
453         454   58  female  37.1      Yes             97       No         3
457         458   50  female  42.9      Yes             98       No         3
458         459   34  female  40.6      Yes             98       No         1
461         462   42  female  23.5       No             94       No         2
463         464   51  female  27.7       No             81       No         3
467         468   59  female  37.9      Yes             91       No         0
468         469   38  female  27.4       No             81       No         1
469         470   53  female  29.8       No             99       No         1
471         472   29  female  36.3      Yes             83       No         3
472         473   31  female  27.3       No             86      Yes         1
473         474   48  female  33.0      Yes             99       No         0
474         475   55  female  34.8      Yes             80      Yes         2
484         485   55  female  23.4       No             85      Yes         2
488         489   54  female  19.0       No             84      Yes         3
489         490   48  female  28.1       No             95      Yes         1
490         491   54  female  32.2      Yes             89       No         1
491         492   40  female  36.1      Yes             80       No         1
498         499   31  female  17.3       No            100       No         2
499         500   60  female  19.5       No             95       No         2
504         505   55  female  25.3       No             91      Yes         1
505         506   34  female  26.2       No             88      Yes         1
506         507   56  female  32.9      Yes             84      Yes         0
507         508   26  female  29.0       No             93       No         1
508         509   33  female  25.5       No             87       No         1
509         510   50  female  20.0       No             89      Yes         2
510         511   55  female  27.8       No             80      Yes         2
513         514   49  female  28.0       No             92       No         3
515         516   27  female  28.3       No             88       No         1
521         522   54  female  26.3       No             89       No         2
522         523   34  female  31.9       No             94       No         2
524         525   29  female  22.1       No             83      Yes         3
525         526   55  female  29.0       No             84      Yes         4
529         530   46  female  27.7       No             83       No         3
530         531   37  female  29.2       No             92       No         0
531         532   25  female  25.1       No             94      Yes         0
532         533   56  female  29.9       No             81      Yes         1
533         534   32  female  33.1      Yes             94      Yes         0
534         535   60  female  35.6      Yes             80       No         1
535         536   37  female  35.3      Yes            100       No         0
536         537   55  female  31.6       No             91       No         1
537         538   26  female  37.1      Yes             88       No         2

# Task-11)

## Find the total claim of insurance based on regions.

In [35]:
df.groupby(by='region')['claim'].sum()

region
North_East    3901369.33
North_West    3948829.61
South_East    5691910.20
South_West    3932313.48
Name: claim, dtype: float64

# Task-12)

## Find the total number of males and females in each region.

In [36]:
df.groupby(by=['region','gender'])['gender'].count()

region      gender
North_East  female    112
            male      119
North_West  female    161
            male      176
South_East  female    221
            male      215
South_West  female    158
            male      153
Name: gender, dtype: int64

In [37]:
# pd.crosstab(df['region'],df['gender'],values=df['claim'],aggfunc=np.mean)

# Task-13)

## Find the average claim of insurance for males and females in each region.

In [38]:
df.groupby(by=['region','gender'])['claim'].mean()  #ORELSE DESCRIBE()

region      gender
North_East  female    16533.758482
            male      17223.431765
North_West  female    12635.087826
            male      10940.459829
South_East  female    11633.502172
            male      14583.673925
South_West  female    11268.901083
            male      14137.882418
Name: claim, dtype: float64

# Task-14)

## Create a pivot table that shows the average claims for each region.

In [39]:
df.head()          # Input data

,patientid,age,gender,bmi,High_bmi,bloodpressure,diabetic,children,smoker,region,claim
0,1,39,male,23.2,No,91,Yes,0,No,South_East,1121.87
1,2,24,male,30.1,No,87,No,0,No,South_East,1131.51
2,3,27,male,33.3,Yes,82,Yes,0,No,South_East,1135.94
3,4,37,male,33.7,Yes,80,No,0,No,North_West,1136.40
4,5,30,male,34.1,Yes,100,No,0,No,North_West,1137.01

In [40]:
Pvt = pd.pivot_table(df, index=['region'], values=['claim'])     # Pivot table
Pvt

                   claim
region
North_East  16889.044719
North_West  11752.469077
South_East  13084.851034
South_West  12684.882194

# Task-15)

## Create a pivot table that shows the minimum and maximum claim for each region.

In [41]:
Pvt1 = pd.pivot_table(df, index=['region'], values=['claim'], aggfunc='min')    # Minimum claim
Pvt1

              claim
region
North_East  1694.80
North_West  1136.40
South_East  1121.87
South_West  1252.41

In [42]:
Pvt2 = pd.pivot_table(df, index=['region'], values=['claim'], aggfunc='max')     # Maximum claim
Pvt2

               claim
region
North_East  58571.07
North_West  60021.40
South_East  63770.43
South_West  52590.83

# Task-16)

## Create a cross table to find out the region-wise gender count.

In [43]:
pd.crosstab(df.region, df.gender, rownames=['region'], colnames=['gender'])

gender      female  male
region
North_East     112   119
North_West     161   176
South_East     221   215
South_West     158   153

# Task-17)

## Find out the total missing values in each column of the dataset. Then replace the missing values by appropriate values.
### Total missing values in each column

In [44]:
#Total missing values in each column
df.isnull().sum()

patientid        0
age              0
gender           0
bmi              0
High_bmi         0
bloodpressure    0
diabetic         5
children         0
smoker           0
region           0
claim            3
dtype: int64

### Count the different values of diabetic column

In [45]:
#Counting the different values of diabetic column
df['diabetic'].value_counts()

No     679
Yes    631
Name: diabetic, dtype: int64

### Replace the missing value by the most frequent value

In [46]:
#replace the missing value by the most frequent value
df['diabetic'] = df['diabetic'].fillna('No')

### Replace the missing value by mean value in 'claim'

In [47]:
#replace the missing value by the mean value
df['claim'] = df['claim'].fillna(df['claim'].mean())

### Find the total missing values in each column again

In [48]:
#Total missing values in each column
df.isnull().sum()

patientid        0
age              0
gender           0
bmi              0
High_bmi         0
bloodpressure    0
diabetic         0
children         0
smoker           0
region           0
claim            0
dtype: int64

### There are no missing values left.